use std::{
    fs::{self, File},
    io::{Cursor, Write},
    path::{Path, PathBuf},
};

use bw_model::{
    V32AdapterEffortRecord, V32RankedCandidateRecord, adapter_effort_from_ranked,
    validate_v3_2_adapter_effort, validate_v3_2_ranked_candidates,
};
use clap::Args;
use serde::Serialize;
use sha2::{Digest, Sha256};

use crate::{
    commands::{DEFAULT_MAX_LINE_BYTES, read_jsonl},
    exit::{CliError, CommandStatus},
};

#[derive(Args)]
pub struct AccountAdapterEffortArgs {
    /// Ranked candidates file (.jsonl/.jsonl.zst) or lifecycle output directory.
    #[arg(long = "ranked-candidates")]
    ranked_candidates: PathBuf,
    #[arg(long = "output-dir")]
    output_dir: PathBuf,
    #[arg(long)]
    run_id: String,
    #[arg(long, default_value_t = DEFAULT_MAX_LINE_BYTES)]
    max_line_bytes: usize,
}

#[derive(Serialize)]
struct AccountAdapterEffortOutput {
    kind: &'static str,
    run_id: String,
    record_count: u64,
    adapter_needed_count: u64,
    deferred_count: u64,
    total_manual_minutes: u64,
    total_generated_lines: u64,
    total_manual_lines: u64,
    output_dir: String,
    adapter_effort_path: String,
    checksums_path: String,
}

pub fn run(args: AccountAdapterEffortArgs) -> Result<CommandStatus, CliError> {
    if args.run_id.trim().is_empty() {
        return Err(CliError::input("BW-ADAPTER-RUN-ID", "run_id 不能为空"));
    }

    let ranked_path = resolve_ranked_path(&args.ranked_candidates)?;
    let ranked_records = read_jsonl::<V32RankedCandidateRecord>(&ranked_path, args.max_line_bytes)?;
    validate_v3_2_ranked_candidates(ranked_records.clone())?;

    let efforts = ranked_records
        .iter()
        .map(|located| adapter_effort_from_ranked(&located.value, &args.run_id))
        .collect::<Vec<_>>();

    let summary =
        validate_v3_2_adapter_effort(efforts.iter().cloned().enumerate().map(|(index, value)| {
            bw_model::Located {
                path: args.output_dir.join("adapter-effort.jsonl.zst"),
                line: index + 1,
                value,
            }
        }))?;

    fs::create_dir_all(&args.output_dir)?;
    let adapter_effort_path = args.output_dir.join("adapter-effort.jsonl.zst");
    write_records(&adapter_effort_path, &efforts)?;

    let stats = serde_json::json!({
        "schema_version": "v3.2.adapter_effort_stats.1",
        "run_id": args.run_id,
        "record_count": summary.record_count,
        "adapter_needed_count": summary.adapter_needed_count,
        "deferred_count": summary.deferred_count,
        "total_manual_minutes": summary.total_manual_minutes,
        "total_generated_lines": summary.total_generated_lines,
        "total_manual_lines": summary.total_manual_lines,
        "effort_class_counts": count_effort_classes(&efforts),
        "adapter_kind_counts": count_adapter_kinds(&efforts),
    });
    write_json_file(&args.output_dir.join("stats.json"), &stats)?;

    let checksums_path = args.output_dir.join("checksums.sha256");
    write_checksums(
        &[
            ("adapter-effort.jsonl.zst", &adapter_effort_path),
            ("stats.json", &args.output_dir.join("stats.json")),
        ],
        &checksums_path,
    )?;

    let output = AccountAdapterEffortOutput {
        kind: "v3-2-adapter-effort",
        run_id: args.run_id,
        record_count: summary.record_count,
        adapter_needed_count: summary.adapter_needed_count,
        deferred_count: summary.deferred_count,
        total_manual_minutes: summary.total_manual_minutes,
        total_generated_lines: summary.total_generated_lines,
        total_manual_lines: summary.total_manual_lines,
        output_dir: args.output_dir.display().to_string(),
        adapter_effort_path: adapter_effort_path.display().to_string(),
        checksums_path: checksums_path.display().to_string(),
    };
    crate::commands::write_json_stdout(&output)?;
    Ok(CommandStatus::Success)
}

fn resolve_ranked_path(path: &Path) -> Result<PathBuf, CliError> {
    if path.is_file() {
        return Ok(path.to_path_buf());
    }
    if path.is_dir() {
        let candidate = path.join("ranked-candidates.jsonl.zst");
        if candidate.is_file() {
            return Ok(candidate);
        }
    }
    Err(CliError::input(
        "BW-IO",
        format!(
            "找不到 ranked-candidates 文件: {} (也可传入包含 ranked-candidates.jsonl.zst 的目录)",
            path.display()
        ),
    ))
}

fn count_effort_classes(
    records: &[V32AdapterEffortRecord],
) -> std::collections::BTreeMap<&'static str, u64> {
    let mut counts = std::collections::BTreeMap::new();
    for record in records {
        let key = match record.effort_class {
            bw_model::V32EffortClass::AutoGenerated => "auto_generated",
            bw_model::V32EffortClass::LightManual => "light_manual",
            bw_model::V32EffortClass::HeavyManual => "heavy_manual",
            bw_model::V32EffortClass::Deferred => "deferred",
        };
        *counts.entry(key).or_default() += 1;
    }
    counts
}

fn count_adapter_kinds(
    records: &[V32AdapterEffortRecord],
) -> std::collections::BTreeMap<&'static str, u64> {
    let mut counts = std::collections::BTreeMap::new();
    for record in records {
        let key = match record.adapter_kind {
            bw_model::V32AdapterKind::None => "none",
            bw_model::V32AdapterKind::MinimalHarness => "minimal_harness",
            bw_model::V32AdapterKind::CallbackHarness => "callback_harness",
            bw_model::V32AdapterKind::PointerHarness => "pointer_harness",
            bw_model::V32AdapterKind::HandleHarness => "handle_harness",
            bw_model::V32AdapterKind::HeavyManualAnalysis => "heavy_manual_analysis",
        };
        *counts.entry(key).or_default() += 1;
    }
    counts
}

fn write_records(path: &Path, records: &[V32AdapterEffortRecord]) -> Result<(), CliError> {
    let mut bytes = Vec::<u8>::new();
    for record in records {
        serde_json::to_writer(&mut bytes, record)
            .map_err(|error| CliError::internal(error.to_string()))?;
        bytes.push(b'\n');
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let file = File::create(path)?;
    if path.extension().is_some_and(|extension| extension == "zst") {
        zstd::stream::copy_encode(Cursor::new(bytes), file, 0)
            .map_err(|error| CliError::input("BW-IO", error.to_string()))?;
    } else {
        let mut file = file;
        file.write_all(&bytes)?;
    }
    Ok(())
}

fn write_json_file(path: &Path, value: &impl Serialize) -> Result<(), CliError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut file = File::create(path)?;
    serde_json::to_writer_pretty(&mut file, value)
        .map_err(|error| CliError::internal(error.to_string()))?;
    file.write_all(b"\n")?;
    Ok(())
}

fn write_checksums(files: &[(&str, &Path)], checksums_path: &Path) -> Result<(), CliError> {
    let mut lines = Vec::<String>::new();
    for (relative, path) in files {
        lines.push(format!("{}  {relative}", sha256_file(path)?));
    }
    lines.sort();
    let mut file = File::create(checksums_path)?;
    for line in lines {
        writeln!(file, "{line}")?;
    }
    Ok(())
}

fn sha256_file(path: &Path) -> Result<String, CliError> {
    let bytes = fs::read(path)
        .map_err(|error| CliError::input("BW-IO", format!("{}: {}", path.display(), error)))?;
    Ok(hex_digest(Sha256::digest(bytes)))
}

fn hex_digest(bytes: impl AsRef<[u8]>) -> String {
    let bytes = bytes.as_ref();
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        use std::fmt::Write as _;
        write!(&mut output, "{byte:02x}").expect("writing to String cannot fail");
    }
    output
}
