use std::collections::BTreeSet;

use serde::{Deserialize, Serialize};

use crate::{
    Located, ModelError, V32PatternFamily, V32RankedCandidateRecord,
    public_tokens::reject_public_forbidden_token,
};

pub const V3_2_ADAPTER_EFFORT_SCHEMA_V1: &str = "v3.2.adapter_effort.1";

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct V32AdapterEffortRecord {
    #[serde(deserialize_with = "crate::schema::deserialize_v3_2_adapter_effort_schema")]
    pub schema_version: String,
    pub run_id: String,
    pub candidate_id: String,
    pub crate_id: String,
    pub pattern_family: V32PatternFamily,
    pub rank: u32,
    pub score: u32,
    pub adapter_needed: bool,
    pub adapter_kind: V32AdapterKind,
    pub effort_class: V32EffortClass,
    pub manual_minutes: u32,
    pub generated_lines: u32,
    pub manual_lines: u32,
    pub blocked_reason: Option<String>,
    #[serde(default)]
    pub notes: Vec<String>,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum V32AdapterKind {
    None,
    MinimalHarness,
    CallbackHarness,
    PointerHarness,
    HandleHarness,
    HeavyManualAnalysis,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum V32EffortClass {
    AutoGenerated,
    LightManual,
    HeavyManual,
    Deferred,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct V32AdapterEffortSummary {
    pub record_count: u64,
    pub adapter_needed_count: u64,
    pub deferred_count: u64,
    pub total_manual_minutes: u64,
    pub total_generated_lines: u64,
    pub total_manual_lines: u64,
}

/// Estimate pilot planning effort from a ranked candidate.
///
/// These values are planning estimates for accounting, not measured human labor
/// and not proof that a vulnerability exists.
pub fn adapter_effort_from_ranked(
    ranked: &V32RankedCandidateRecord,
    run_id: &str,
) -> V32AdapterEffortRecord {
    let dynamic_ready = ranked.score >= 20
        || ranked.risk_features.callback_retained_across_drop
        || ranked.risk_features.foreign_retention_without_owned_anchor
        || ranked.risk_features.opaque_handle_without_owner;

    if !dynamic_ready {
        return V32AdapterEffortRecord {
            schema_version: V3_2_ADAPTER_EFFORT_SCHEMA_V1.to_owned(),
            run_id: run_id.to_owned(),
            candidate_id: ranked.candidate_id.clone(),
            crate_id: ranked.crate_id.clone(),
            pattern_family: ranked.pattern_family,
            rank: ranked.rank,
            score: ranked.score,
            adapter_needed: false,
            adapter_kind: V32AdapterKind::None,
            effort_class: V32EffortClass::Deferred,
            manual_minutes: 0,
            generated_lines: 0,
            manual_lines: 0,
            blocked_reason: Some("static_only_deferred".to_owned()),
            notes: base_notes("deferred because ranking score and risk features stay static-only"),
        };
    }

    let (adapter_kind, effort_class, manual_minutes, generated_lines, manual_lines) =
        estimate_budget(ranked.pattern_family, ranked.score);

    V32AdapterEffortRecord {
        schema_version: V3_2_ADAPTER_EFFORT_SCHEMA_V1.to_owned(),
        run_id: run_id.to_owned(),
        candidate_id: ranked.candidate_id.clone(),
        crate_id: ranked.crate_id.clone(),
        pattern_family: ranked.pattern_family,
        rank: ranked.rank,
        score: ranked.score,
        adapter_needed: true,
        adapter_kind,
        effort_class,
        manual_minutes,
        generated_lines,
        manual_lines,
        blocked_reason: None,
        notes: base_notes("dynamic-validation preparation estimate for pilot accounting"),
    }
}

pub fn validate_v3_2_adapter_effort<I>(records: I) -> Result<V32AdapterEffortSummary, ModelError>
where
    I: IntoIterator<Item = Located<V32AdapterEffortRecord>>,
{
    let mut summary = V32AdapterEffortSummary::default();
    let mut run_id: Option<String> = None;
    let mut candidate_ids = BTreeSet::<String>::new();

    for located in records {
        let record = &located.value;
        validate_required_text(&located, "run_id", &record.run_id)?;
        validate_required_text(&located, "candidate_id", &record.candidate_id)?;
        validate_required_text(&located, "crate_id", &record.crate_id)?;
        reject_private_tokens(&located, "run_id", &record.run_id)?;
        reject_private_tokens(&located, "candidate_id", &record.candidate_id)?;
        reject_private_tokens(&located, "crate_id", &record.crate_id)?;
        for note in &record.notes {
            reject_private_tokens(&located, "notes", note)?;
        }
        if let Some(reason) = &record.blocked_reason {
            validate_required_text(&located, "blocked_reason", reason)?;
            reject_private_tokens(&located, "blocked_reason", reason)?;
        }

        if record.rank == 0 {
            return Err(at(&located, "BW-ADAPTER-RANK-ZERO", "rank 必须从 1 开始"));
        }

        if let Some(expected) = &run_id {
            if expected != &record.run_id {
                return Err(at(
                    &located,
                    "BW-ADAPTER-RUN-MISMATCH",
                    format!(
                        "同一 adapter-effort 文件出现 run_id {expected} 和 {}",
                        record.run_id
                    ),
                ));
            }
        } else {
            run_id = Some(record.run_id.clone());
        }

        if !candidate_ids.insert(record.candidate_id.clone()) {
            return Err(at(
                &located,
                "BW-ADAPTER-CANDIDATE-DUPLICATE",
                format!("candidate_id {} 重复", record.candidate_id),
            ));
        }

        if record.adapter_needed {
            if record.adapter_kind == V32AdapterKind::None {
                return Err(at(
                    &located,
                    "BW-ADAPTER-KIND",
                    "adapter_needed=true 时 adapter_kind 不能是 none",
                ));
            }
            if record.effort_class == V32EffortClass::Deferred {
                return Err(at(
                    &located,
                    "BW-ADAPTER-EFFORT-CLASS",
                    "adapter_needed=true 时 effort_class 不能是 deferred",
                ));
            }
            if record.blocked_reason.is_some() {
                return Err(at(
                    &located,
                    "BW-ADAPTER-BLOCKED",
                    "adapter_needed=true 时 blocked_reason 必须为 null",
                ));
            }
            summary.adapter_needed_count += 1;
        } else {
            if record.adapter_kind != V32AdapterKind::None {
                return Err(at(
                    &located,
                    "BW-ADAPTER-KIND",
                    "adapter_needed=false 时 adapter_kind 必须是 none",
                ));
            }
            if record.effort_class != V32EffortClass::Deferred {
                return Err(at(
                    &located,
                    "BW-ADAPTER-EFFORT-CLASS",
                    "adapter_needed=false 时 effort_class 必须是 deferred",
                ));
            }
            if record.blocked_reason.is_none() {
                return Err(at(
                    &located,
                    "BW-ADAPTER-BLOCKED",
                    "adapter_needed=false 时必须填写 blocked_reason",
                ));
            }
            if record.manual_minutes != 0 || record.generated_lines != 0 || record.manual_lines != 0
            {
                return Err(at(
                    &located,
                    "BW-ADAPTER-ZERO-COST",
                    "deferred 记录的 manual/generated 成本必须为 0",
                ));
            }
            summary.deferred_count += 1;
        }

        summary.total_manual_minutes += u64::from(record.manual_minutes);
        summary.total_generated_lines += u64::from(record.generated_lines);
        summary.total_manual_lines += u64::from(record.manual_lines);
        summary.record_count += 1;
    }

    Ok(summary)
}

fn estimate_budget(
    pattern_family: V32PatternFamily,
    score: u32,
) -> (V32AdapterKind, V32EffortClass, u32, u32, u32) {
    let adapter_kind = match pattern_family {
        V32PatternFamily::RetainedBorrowedCallback | V32PatternFamily::CallbackLifecycleRelease => {
            V32AdapterKind::CallbackHarness
        }
        V32PatternFamily::ForeignRetainedPointer | V32PatternFamily::ExternalBufferView => {
            V32AdapterKind::PointerHarness
        }
        V32PatternFamily::OpaqueHandleTransfer => V32AdapterKind::HandleHarness,
        V32PatternFamily::NativeLibraryBoundary | V32PatternFamily::ReturnedBorrowView => {
            V32AdapterKind::MinimalHarness
        }
    };

    if score >= 40 {
        (
            if matches!(
                pattern_family,
                V32PatternFamily::RetainedBorrowedCallback
                    | V32PatternFamily::ForeignRetainedPointer
                    | V32PatternFamily::ExternalBufferView
            ) {
                V32AdapterKind::HeavyManualAnalysis
            } else {
                adapter_kind
            },
            V32EffortClass::HeavyManual,
            60,
            180,
            40,
        )
    } else if score >= 20 {
        (adapter_kind, V32EffortClass::LightManual, 30, 120, 18)
    } else {
        (
            V32AdapterKind::MinimalHarness,
            V32EffortClass::AutoGenerated,
            10,
            80,
            5,
        )
    }
}

fn base_notes(detail: &str) -> Vec<String> {
    vec![
        "adapter must not become a hidden answer channel".to_owned(),
        "effort values are pilot planning estimates, not measured labor".to_owned(),
        "adapter effort is not a vulnerability conclusion".to_owned(),
        detail.to_owned(),
    ]
}

fn validate_required_text(
    located: &Located<V32AdapterEffortRecord>,
    field: &'static str,
    value: &str,
) -> Result<(), ModelError> {
    if value.trim().is_empty() {
        return Err(at(
            located,
            "BW-ADAPTER-REQUIRED-EMPTY",
            format!("{field} 不能为空"),
        ));
    }
    Ok(())
}

fn reject_private_tokens(
    located: &Located<V32AdapterEffortRecord>,
    field: &'static str,
    value: &str,
) -> Result<(), ModelError> {
    reject_public_forbidden_token(field, value)
        .map_err(|message| at(located, "BW-ADAPTER-PRIVATE-TOKEN", message))
}

fn at(
    located: &Located<V32AdapterEffortRecord>,
    code: &'static str,
    message: impl Into<String>,
) -> ModelError {
    ModelError::validation(code, message).at_line(located.path.clone(), located.line)
}
